SSL: true
USE_AMP: true
AUGMENTATION:
  STRENGTH: 1.0
  BRIGHTNESS: true
  BRIGHTNESS_MAX_DELTA: 0.8
  CONTRAST: true
  CONTRAST_MAX_DELTA: 0.8
  HUE: true
  HUE_MAX_DELTA: 0.2
  RANDOM_CROP: true
  RANDOM_FLIP: true
  SATURATION: true
  SATURATION_MAX_DELTA: 0.8
CHECKPOINT:
  SAVE_INTERVAL: 60
DATA:
  FRAME_LABELS: true
  NUM_CONTEXTS: 1
  CONTEXT_STRIDE: 1
  NUM_WORKERS: 4
  SAMPLE_ALL_STRIDE: 1
  SAMPLING_STRATEGY: time_augment
  SAMPLING_REGION: 1.5
  CONSISTENT_OFFSET: 0.2
DATASETS:
- baseball_pitch
- baseball_swing
- bench_press
- bowl
- clean_and_jerk
- golf_swing
- jumping_jacks
- pushup
- pullup
- situp
- squat
- tennis_forehand
- tennis_serve
EVAL:
  BATCH_SIZE: 1
  CLASSIFICATION_FRACTIONS:
  - 1.0
  FRAMES_PER_BATCH: 1000
  KENDALLS_TAU_DISTANCE: sqeuclidean
  KENDALLS_TAU_STRIDE: 2
  RETRIEVAL_KS: 
  - 5
  - 10
  - 15
  NUM_FRAMES: 80
  TASKS:
  - kendalls_tau
  - retrieval
  - classification
  - event_completion
  VAL_INTERVAL: 50
IMAGE_SIZE: 224
LOGDIR: /tmp/scl_transformer_action_logs
LOGGING:
  REPORT_INTERVAL: 20
MODEL:
  BASE_MODEL:
    LAYER: 3
    NETWORK: Resnet50_byol
    FRAMES_PER_BATCH: 40
  EMBEDDER_MODEL:
    HIDDEN_SIZE: 256
    D_FF: 1024
    NUM_HEADS: 8
    NUM_LAYERS: 3
    CAPACITY_SCALAR: 2
    CONV_LAYERS:
    - &id002
      - 256
      - 3
      - 1
    - *id002
    EMBEDDING_SIZE: 128
    FC_DROPOUT_RATE: 0.1
    FC_LAYERS:
    - &id003
      - 256
      - true
    - *id003
    FLATTEN_METHOD: max_pool
    USE_BN: true
  EMBEDDER_TYPE: transformer
  L2_NORMALIZE: true
  PROJECTION: true
  PROJECTION_HIDDEN_SIZE: 512
  PROJECTION_SIZE: 128
  TRAIN_BASE: frozen
NUM_GPUS: 1
OPTIMIZER:
  GRAD_CLIP: 10
  LR:
    DECAY_TYPE: cosine
    INITIAL_LR: 0.0001
    NUM_WARMUP_STEPS: 1
    WARMUP_LR: 0.0
    FINAL_LR: 0.0
  TYPE: AdamOptimizer
  WEIGHT_DECAY: 1.0e-05
PATH_TO_DATASET: 'penn_action'
RNG_SEED: 1
SHARD_ID: 0
SCL:
  LABEL_VARIENCE: 10.0
  POSITIVE_TYPE: gauss
  NEGATIVE_TYPE: single_noself
  SOFTMAX_TEMPERATURE: 0.1
  POSITIVE_WINDOW: 5
TRAIN:
  BATCH_SIZE: 1
  MAX_EPOCHS: 300
  NUM_FRAMES: 80
TRAINING_ALGO: scl
